<?xml version="1.0" encoding="utf-8" standalone="no"?>
<test-run id="2" testcasecount="24" result="Failed" total="23" passed="9" failed="11" inconclusive="0" skipped="3" asserts="5" engine-version="3.10.0.0" clr-version="4.0.30319.42000" start-time="2019-06-26 09:58:55Z" end-time="2019-06-26 09:59:12Z" duration="17.129134">
  <command-line><![CDATA["C:\Program Files (x86)\NUnit.org\nunit-console\nunit3-console.exe" /out:results.xml Example.dll]]></command-line>
  <test-suite type="Assembly" id="0-1033" name="Example.dll" fullname="C:\Users\v.kostyukevich\Downloads\example-net-nunit-master\src\Example\bin\Debug\Example.dll" runstate="Runnable" testcasecount="24" result="Failed" site="Child" start-time="2019-06-26 09:58:56Z" end-time="2019-06-26 09:59:12Z" duration="16.408045" total="23" passed="9" failed="11" warnings="1" inconclusive="0" skipped="3" asserts="5">
    <environment framework-version="3.12.0.0" clr-version="4.0.30319.42000" os-version="Microsoft Windows NT 10.0.17763.0" platform="Win32NT" cwd="C:\Users\v.kostyukevich\Downloads\example-net-nunit-master\src\Example\bin\Debug" machine-name="KOSTYUKEVICHV" user="v.kostyukevich" user-domain="ITRANSITION" culture="ru-RU" uiculture="en-US" os-architecture="x64" />
    <settings>
      <setting name="DisposeRunners" value="True" />
      <setting name="WorkDirectory" value="C:\Users\v.kostyukevich\Downloads\example-net-nunit-master\src\Example\bin\Debug" />
      <setting name="ImageRuntimeVersion" value="4.0.30319" />
      <setting name="ImageTargetFrameworkName" value=".NETFramework,Version=v4.5" />
      <setting name="ImageRequiresX86" value="False" />
      <setting name="ImageRequiresDefaultAppDomainAssemblyResolver" value="False" />
      <setting name="NumberOfTestWorkers" value="6" />
    </settings>
    <properties>
      <property name="_PID" value="20500" />
      <property name="_APPDOMAIN" value="domain-" />
    </properties>
    <failure>
      <message><![CDATA[One or more child tests had errors]]></message>
    </failure>
    <test-suite type="TestSuite" id="0-1034" name="Example" fullname="Example" runstate="Runnable" testcasecount="24" result="Failed" site="Child" start-time="2019-06-26 09:58:56Z" end-time="2019-06-26 09:59:12Z" duration="16.391212" total="23" passed="9" failed="11" warnings="1" inconclusive="0" skipped="3" asserts="5">
      <failure>
        <message><![CDATA[One or more child tests had errors]]></message>
      </failure>
      <test-suite type="TestSuite" id="0-1035" name="Tests" fullname="Example.Tests" runstate="Runnable" testcasecount="24" result="Failed" site="Child" start-time="2019-06-26 09:58:56Z" end-time="2019-06-26 09:59:12Z" duration="16.390804" total="23" passed="9" failed="11" warnings="1" inconclusive="0" skipped="3" asserts="5">
        <failure>
          <message><![CDATA[One or more child tests had errors]]></message>
        </failure>
        <test-suite type="TestFixture" id="0-1007" name="EmptyClass" fullname="Example.Tests.EmptyClass" classname="Example.Tests.EmptyClass" runstate="Runnable" testcasecount="0" result="Passed" start-time="2019-06-26 09:58:56Z" end-time="2019-06-26 09:58:56Z" duration="0.001045" total="0" passed="0" failed="0" warnings="0" inconclusive="0" skipped="0" asserts="0">
          <properties>
            <property name="Category" value="Category 1" />
            <property name="Category" value="Category 2" />
            <property name="Description" value="Empty suite" />
          </properties>
        </test-suite>
        <test-suite type="TestFixture" id="0-1000" name="Class3" fullname="Example.Tests.Class3" classname="Example.Tests.Class3" runstate="Runnable" testcasecount="3" result="Failed" label="Error" site="SetUp" start-time="2019-06-26 09:58:56Z" end-time="2019-06-26 09:58:56Z" duration="0.189286" total="3" passed="0" failed="3" warnings="0" inconclusive="0" skipped="0" asserts="0">
          <properties>
            <property name="ParallelScope" value="Self" />
          </properties>
          <failure>
            <message><![CDATA[System.Exception : Setup exception.]]></message>
            <stack-trace><![CDATA[   at Example.Tests.Class3.OneTimeSetUp() in C:\Users\v.kostyukevich\Downloads\example-net-nunit-master\src\Example\Tests\Class3.cs:line 20]]></stack-trace>
          </failure>
          <test-case id="0-1001" name="Test1" fullname="Example.Tests.Class3.Test1" methodname="Test1" classname="Example.Tests.Class3" runstate="Runnable" seed="305656054" result="Failed" label="Error" site="Parent" start-time="0001-01-01 00:00:00Z" end-time="0001-01-01 00:00:00Z" duration="0.000000" asserts="0">
            <failure>
              <message><![CDATA[OneTimeSetUp: System.Exception : Setup exception.]]></message>
            </failure>
          </test-case>
          <test-case id="0-1002" name="Test2" fullname="Example.Tests.Class3.Test2" methodname="Test2" classname="Example.Tests.Class3" runstate="Runnable" seed="2056328827" result="Failed" label="Error" site="Parent" start-time="0001-01-01 00:00:00Z" end-time="0001-01-01 00:00:00Z" duration="0.000000" asserts="0">
            <failure>
              <message><![CDATA[OneTimeSetUp: System.Exception : Setup exception.]]></message>
            </failure>
          </test-case>
          <test-case id="0-1003" name="Test3" fullname="Example.Tests.Class3.Test3" methodname="Test3" classname="Example.Tests.Class3" runstate="Runnable" seed="17175986" result="Failed" label="Error" site="Parent" start-time="0001-01-01 00:00:00Z" end-time="0001-01-01 00:00:00Z" duration="0.000000" asserts="0">
            <failure>
              <message><![CDATA[OneTimeSetUp: System.Exception : Setup exception.]]></message>
            </failure>
          </test-case>
        </test-suite>
        <test-suite type="TestFixture" id="0-1011" name="Class2" fullname="Example.Tests.Class2" classname="Example.Tests.Class2" runstate="Runnable" testcasecount="10" result="Failed" site="Child" start-time="2019-06-26 09:58:56Z" end-time="2019-06-26 09:58:56Z" duration="0.383744" total="9" passed="6" failed="2" warnings="1" inconclusive="0" skipped="1" asserts="0">
          <properties>
            <property name="ParallelScope" value="Self" />
            <property name="Category" value="Category 1" />
            <property name="Category" value="Category 2" />
          </properties>
          <failure>
            <message><![CDATA[One or more child tests had errors]]></message>
          </failure>
          <test-case id="0-1017" name="IgnoredTest" fullname="Example.Tests.Class2.IgnoredTest" methodname="IgnoredTest" classname="Example.Tests.Class2" runstate="Ignored" seed="1529885186" result="Skipped" label="Ignored" start-time="2019-06-26 09:58:56Z" end-time="2019-06-26 09:58:56Z" duration="0.004924" asserts="0">
            <properties>
              <property name="_SKIPREASON" value="My ignore reason" />
            </properties>
            <reason>
              <message><![CDATA[My ignore reason]]></message>
            </reason>
          </test-case>
          <test-case id="0-1018" name="SyncTest" fullname="Example.Tests.Class2.SyncTest" methodname="SyncTest" classname="Example.Tests.Class2" runstate="Runnable" seed="1075964987" result="Passed" start-time="2019-06-26 09:58:56Z" end-time="2019-06-26 09:58:56Z" duration="0.006286" asserts="0">
            <properties>
              <property name="Description" value="This test should have actual unique ID in logs assigned by server" />
            </properties>
          </test-case>
          <test-case id="0-1012" name="Test1" fullname="Example.Tests.Class2.Test1" methodname="Test1" classname="Example.Tests.Class2" runstate="Runnable" seed="1655589633" result="Passed" start-time="2019-06-26 09:58:56Z" end-time="2019-06-26 09:58:56Z" duration="0.313304" asserts="0" />
          <test-case id="0-1013" name="Test2" fullname="Example.Tests.Class2.Test2" methodname="Test2" classname="Example.Tests.Class2" runstate="Runnable" seed="59489005" result="Warning" start-time="2019-06-26 09:58:56Z" end-time="2019-06-26 09:58:56Z" duration="0.037440" asserts="0">
            <reason>
              <message><![CDATA[My warn message]]></message>
            </reason>
            <assertions>
              <assertion result="Warning">
                <message><![CDATA[My warn message]]></message>
                <stack-trace><![CDATA[   at Example.Tests.Class2.Test2() in C:\Users\v.kostyukevich\Downloads\example-net-nunit-master\src\Example\Tests\Class2.cs:line 26
]]></stack-trace>
              </assertion>
            </assertions>
          </test-case>
          <test-case id="0-1014" name="Test3" fullname="Example.Tests.Class2.Test3" methodname="Test3" classname="Example.Tests.Class2" runstate="Runnable" seed="1609631688" result="Failed" start-time="2019-06-26 09:58:56Z" end-time="2019-06-26 09:58:56Z" duration="0.005441" asserts="0">
            <failure>
              <message><![CDATA[test failed.]]></message>
              <stack-trace><![CDATA[   at Example.Tests.Class2.Test3() in C:\Users\v.kostyukevich\Downloads\example-net-nunit-master\src\Example\Tests\Class2.cs:line 32
]]></stack-trace>
            </failure>
            <assertions>
              <assertion result="Failed">
                <message><![CDATA[test failed.]]></message>
                <stack-trace><![CDATA[   at Example.Tests.Class2.Test3() in C:\Users\v.kostyukevich\Downloads\example-net-nunit-master\src\Example\Tests\Class2.cs:line 32
]]></stack-trace>
              </assertion>
            </assertions>
          </test-case>
          <test-case id="0-1015" name="Test3FailedWithoutMessage" fullname="Example.Tests.Class2.Test3FailedWithoutMessage" methodname="Test3FailedWithoutMessage" classname="Example.Tests.Class2" runstate="Runnable" seed="1582752951" result="Failed" start-time="2019-06-26 09:58:56Z" end-time="2019-06-26 09:58:56Z" duration="0.000693" asserts="0">
            <failure>
              <stack-trace><![CDATA[   at Example.Tests.Class2.Test3FailedWithoutMessage() in C:\Users\v.kostyukevich\Downloads\example-net-nunit-master\src\Example\Tests\Class2.cs:line 38
]]></stack-trace>
            </failure>
            <assertions>
              <assertion result="Failed">
                <message><![CDATA[]]></message>
                <stack-trace><![CDATA[   at Example.Tests.Class2.Test3FailedWithoutMessage() in C:\Users\v.kostyukevich\Downloads\example-net-nunit-master\src\Example\Tests\Class2.cs:line 38
]]></stack-trace>
              </assertion>
            </assertions>
          </test-case>
          <test-case id="0-1016" name="Test4" fullname="Example.Tests.Class2.Test4" methodname="Test4" classname="Example.Tests.Class2" runstate="Runnable" seed="1189733790" result="Passed" start-time="2019-06-26 09:58:56Z" end-time="2019-06-26 09:58:56Z" duration="0.000084" asserts="0">
            <properties>
              <property name="Description" value="My static description, and this test was executed on {MachineName} machine." />
            </properties>
          </test-case>
          <test-suite type="ParameterizedMethod" id="0-1022" name="TestWithTestCaseSource" fullname="Example.Tests.Class2.TestWithTestCaseSource" classname="Example.Tests.Class2" runstate="Runnable" testcasecount="3" result="Passed" start-time="2019-06-26 09:58:56Z" end-time="2019-06-26 09:58:56Z" duration="0.002100" total="3" passed="3" failed="0" warnings="0" inconclusive="0" skipped="0" asserts="0">
            <test-case id="0-1019" name="TestWithTestCaseSource(0)" fullname="Example.Tests.Class2.TestWithTestCaseSource(0)" methodname="TestWithTestCaseSource" classname="Example.Tests.Class2" runstate="Runnable" seed="1378928024" result="Passed" start-time="2019-06-26 09:58:56Z" end-time="2019-06-26 09:58:56Z" duration="0.000102" asserts="0" />
            <test-case id="0-1020" name="TestWithTestCaseSource(1)" fullname="Example.Tests.Class2.TestWithTestCaseSource(1)" methodname="TestWithTestCaseSource" classname="Example.Tests.Class2" runstate="Runnable" seed="1158611702" result="Passed" start-time="2019-06-26 09:58:56Z" end-time="2019-06-26 09:58:56Z" duration="0.000031" asserts="0" />
            <test-case id="0-1021" name="TestWithTestCaseSource(2)" fullname="Example.Tests.Class2.TestWithTestCaseSource(2)" methodname="TestWithTestCaseSource" classname="Example.Tests.Class2" runstate="Runnable" seed="1539326463" result="Passed" start-time="2019-06-26 09:58:56Z" end-time="2019-06-26 09:58:56Z" duration="0.000037" asserts="0" />
          </test-suite>
        </test-suite>
        <test-suite type="TestFixture" id="0-1023" name="Class1" fullname="Example.Tests.Class1" classname="Example.Tests.Class1" runstate="Runnable" testcasecount="5" result="Failed" site="Child" start-time="2019-06-26 09:58:56Z" end-time="2019-06-26 09:59:12Z" duration="16.376484" total="5" passed="3" failed="2" warnings="0" inconclusive="0" skipped="0" asserts="5">
          <properties>
            <property name="ParallelScope" value="Self" />
            <property name="Description" value="this is description for Class1" />
          </properties>
          <failure>
            <message><![CDATA[One or more child tests had errors]]></message>
          </failure>
          <test-case id="0-1028" name="AttachmentsAreOptional" fullname="Example.Tests.Class1.AttachmentsAreOptional" methodname="AttachmentsAreOptional" classname="Example.Tests.Class1" runstate="Runnable" seed="1031730154" result="Passed" start-time="2019-06-26 09:58:56Z" end-time="2019-06-26 09:58:56Z" duration="0.002473" asserts="0">
            <properties>
              <property name="Description" value="Reporting should work even if file attachment was deleted in runtime." />
            </properties>
            <attachments>
              <attachment>
                <filePath>C:\Users\v.kostyukevich\AppData\Local\Temp\tmpC269.tmp</filePath>
              </attachment>
            </attachments>
          </test-case>
          <test-case id="0-1024" name="Test1" fullname="Example.Tests.Class1.Test1" methodname="Test1" classname="Example.Tests.Class1" runstate="Runnable" seed="651239787" result="Passed" start-time="2019-06-26 09:58:56Z" end-time="2019-06-26 09:58:56Z" duration="0.071031" asserts="0">
            <properties>
              <property name="Category" value="T1" />
            </properties>
            <attachments>
              <attachment>
                <filePath>C:\Users\v.kostyukevich\Downloads\example-net-nunit-master\src\Example\bin\Debug\dog.png</filePath>
                <description><![CDATA[my dog]]></description>
              </attachment>
            </attachments>
          </test-case>
          <test-case id="0-1025" name="Test2" fullname="Example.Tests.Class1.Test2" methodname="Test2" classname="Example.Tests.Class1" runstate="Runnable" seed="1389766155" result="Passed" start-time="2019-06-26 09:58:56Z" end-time="2019-06-26 09:58:56Z" duration="0.000127" asserts="0">
            <properties>
              <property name="Description" value="this is description for Test2" />
            </properties>
          </test-case>
          <test-case id="0-1026" name="Test3" fullname="Example.Tests.Class1.Test3" methodname="Test3" classname="Example.Tests.Class1" runstate="Runnable" seed="1437368620" result="Failed" start-time="2019-06-26 09:58:56Z" end-time="2019-06-26 09:58:57Z" duration="1.007752" asserts="0">
            <properties>
              <property name="Description" value="Test should fail with timeout" />
              <property name="Timeout" value="1000" />
            </properties>
            <failure>
              <message><![CDATA[Test exceeded Timeout value of 1000ms]]></message>
            </failure>
          </test-case>
          <test-case id="0-1027" name="Test4" fullname="Example.Tests.Class1.Test4" methodname="Test4" classname="Example.Tests.Class1" runstate="Runnable" seed="119213841" result="Failed" start-time="2019-06-26 09:58:57Z" end-time="2019-06-26 09:59:12Z" duration="15.020583" asserts="5">
            <properties>
              <property name="Description" value="Test should be retried" />
            </properties>
            <failure>
              <message><![CDATA[  Expected: True
  But was:  False
]]></message>
              <stack-trace><![CDATA[   at Example.Tests.Class1.Test4() in C:\Users\v.kostyukevich\Downloads\example-net-nunit-master\src\Example\Tests\Class1.cs:line 59
]]></stack-trace>
            </failure>
            <assertions>
              <assertion result="Failed">
                <message><![CDATA[  Expected: True
  But was:  False
]]></message>
                <stack-trace><![CDATA[   at Example.Tests.Class1.Test4() in C:\Users\v.kostyukevich\Downloads\example-net-nunit-master\src\Example\Tests\Class1.cs:line 59
]]></stack-trace>
              </assertion>
            </assertions>
          </test-case>
        </test-suite>
        <test-suite type="TestFixture" id="0-1004" name="FailedClass" fullname="Example.Tests.FailedClass" classname="Example.Tests.FailedClass" runstate="Runnable" testcasecount="2" result="Failed" label="Error" site="SetUp" start-time="2019-06-26 09:59:12Z" end-time="2019-06-26 09:59:12Z" duration="0.000590" total="2" passed="0" failed="2" warnings="0" inconclusive="0" skipped="0" asserts="0">
          <properties>
            <property name="Category" value="Category 1" />
            <property name="Category" value="Category 2" />
            <property name="Description" value="This suite throws an exception in OneTimeSetup" />
          </properties>
          <failure>
            <message><![CDATA[System.Exception : Here is OneTimeSetup exception.]]></message>
            <stack-trace><![CDATA[   at Example.Tests.FailedClass.Init() in C:\Users\v.kostyukevich\Downloads\example-net-nunit-master\src\Example\Tests\FailedClass.cs:line 20]]></stack-trace>
          </failure>
          <test-case id="0-1005" name="Test1" fullname="Example.Tests.FailedClass.Test1" methodname="Test1" classname="Example.Tests.FailedClass" runstate="Runnable" seed="1079561307" result="Failed" label="Error" site="Parent" start-time="0001-01-01 00:00:00Z" end-time="0001-01-01 00:00:00Z" duration="0.000000" asserts="0">
            <failure>
              <message><![CDATA[OneTimeSetUp: System.Exception : Here is OneTimeSetup exception.]]></message>
            </failure>
          </test-case>
          <test-case id="0-1006" name="Test2" fullname="Example.Tests.FailedClass.Test2" methodname="Test2" classname="Example.Tests.FailedClass" runstate="Runnable" seed="499085457" result="Failed" label="Error" site="Parent" start-time="0001-01-01 00:00:00Z" end-time="0001-01-01 00:00:00Z" duration="0.000000" asserts="0">
            <failure>
              <message><![CDATA[OneTimeSetUp: System.Exception : Here is OneTimeSetup exception.]]></message>
            </failure>
          </test-case>
        </test-suite>
        <test-suite type="TestFixture" id="0-1008" name="IgnoredClass" fullname="Example.Tests.IgnoredClass" classname="Example.Tests.IgnoredClass" runstate="Ignored" testcasecount="2" result="Skipped" label="Ignored" site="SetUp" start-time="2019-06-26 09:59:12Z" end-time="2019-06-26 09:59:12Z" duration="0.000364" total="2" passed="0" failed="0" warnings="0" inconclusive="0" skipped="2" asserts="0">
          <properties>
            <property name="Category" value="Category 1" />
            <property name="Category" value="Category 2" />
            <property name="_SKIPREASON" value="Ignore reason for suite" />
            <property name="Description" value="All tests in this suite should be skipped." />
          </properties>
          <reason>
            <message><![CDATA[Ignore reason for suite]]></message>
          </reason>
          <test-case id="0-1009" name="Test1" fullname="Example.Tests.IgnoredClass.Test1" methodname="Test1" classname="Example.Tests.IgnoredClass" runstate="Runnable" seed="500641447" result="Skipped" label="Ignored" site="Parent" start-time="0001-01-01 00:00:00Z" end-time="0001-01-01 00:00:00Z" duration="0.000000" asserts="0">
            <reason>
              <message><![CDATA[OneTimeSetUp: Ignore reason for suite]]></message>
            </reason>
          </test-case>
          <test-case id="0-1010" name="Test2" fullname="Example.Tests.IgnoredClass.Test2" methodname="Test2" classname="Example.Tests.IgnoredClass" runstate="Runnable" seed="1214011813" result="Skipped" label="Ignored" site="Parent" start-time="0001-01-01 00:00:00Z" end-time="0001-01-01 00:00:00Z" duration="0.000000" asserts="0">
            <reason>
              <message><![CDATA[OneTimeSetUp: Ignore reason for suite]]></message>
            </reason>
          </test-case>
        </test-suite>
        <test-suite type="SetUpFixture" id="0-1032" name="InnerFolder" fullname="Example.Tests.InnerFolder.ClassFixtureSetup" classname="Example.Tests.InnerFolder.ClassFixtureSetup" runstate="Runnable" testcasecount="2" result="Failed" label="Error" site="TearDown" start-time="2019-06-26 09:59:12Z" end-time="2019-06-26 09:59:12Z" duration="0.001474" total="2" passed="0" failed="2" warnings="0" inconclusive="0" skipped="0" asserts="0">
          <failure>
            <message><![CDATA[System.Exception : Assembly SetUpFixture exception.
TearDown : System.Exception : Assembly TearDownFixture exception.]]></message>
            <stack-trace><![CDATA[   at Example.Tests.InnerFolder.ClassFixtureSetup.OneTimeSetUp() in C:\Users\v.kostyukevich\Downloads\example-net-nunit-master\src\Example\Tests\InnerFolder\ClassFixtureSetup.cs:line 19
--TearDown
   at Example.Tests.InnerFolder.ClassFixtureSetup.OneTimeTearDown() in C:\Users\v.kostyukevich\Downloads\example-net-nunit-master\src\Example\Tests\InnerFolder\ClassFixtureSetup.cs:line 26]]></stack-trace>
          </failure>
          <test-suite type="TestFixture" id="0-1029" name="Class1" fullname="Example.Tests.InnerFolder.Class1" classname="Example.Tests.InnerFolder.Class1" runstate="Runnable" testcasecount="2" result="Failed" label="Error" site="Parent" start-time="0001-01-01 00:00:00Z" end-time="0001-01-01 00:00:00Z" duration="0.000000" total="0" passed="0" failed="0" warnings="0" inconclusive="0" skipped="0" asserts="0">
            <failure>
              <message><![CDATA[OneTimeSetUp: System.Exception : Assembly SetUpFixture exception.]]></message>
            </failure>
          </test-suite>
          <test-case id="0-1030" name="Test1" fullname="Example.Tests.InnerFolder.Class1.Test1" methodname="Test1" classname="Example.Tests.InnerFolder.Class1" runstate="Runnable" seed="872603109" result="Failed" label="Error" site="Parent" start-time="0001-01-01 00:00:00Z" end-time="0001-01-01 00:00:00Z" duration="0.000000" asserts="0">
            <failure>
              <message><![CDATA[OneTimeSetUp: System.Exception : Assembly SetUpFixture exception.]]></message>
            </failure>
          </test-case>
          <test-case id="0-1031" name="Test2" fullname="Example.Tests.InnerFolder.Class1.Test2" methodname="Test2" classname="Example.Tests.InnerFolder.Class1" runstate="Runnable" seed="831412912" result="Failed" label="Error" site="Parent" start-time="0001-01-01 00:00:00Z" end-time="0001-01-01 00:00:00Z" duration="0.000000" asserts="0">
            <failure>
              <message><![CDATA[OneTimeSetUp: System.Exception : Assembly SetUpFixture exception.]]></message>
            </failure>
          </test-case>
        </test-suite>
      </test-suite>
    </test-suite>
  </test-suite>
</test-run>